# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=50, verbose_name='期数')),
                ('postdate', models.DateTimeField(blank=True, null=True, verbose_name='投稿日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=2, verbose_name='性别')),
                ('idnum', models.IntegerField(verbose_name='序号')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('dec', models.TextField(verbose_name='自我介绍')),
                ('image_urls', models.TextField(verbose_name='图片地址')),
            ],
            options={
                'ordering': ['-postdate'],
            },
        ),
    ]
